program proyectointegrador;

{$mode ObjFPC}{$H+}

uses prueba;

begin
     programaPrueba();
end.
//asdasasdasddasasasdasdsasdasssssssssssssdasdsasdasssssdsasdsasasdsasdsssssssssssssssssssssssssassdasssssssssssssssssdasdasdasdasdASDasASASDASDASASsasdasdsasssasdsassssssssssssd
//instantsfpc proysssssssectoinstegrsdorsssssssssssssssssssssssssssssssssssssssssss