program proyectointegrador;

uses analizadorlexico, tablasimbolos, analizadorsintactico, prueba;

begin
     analizarFuente();
end.
//asdasasdasddasasasdasdasdasdasdsasdadsasdsasasdsasdsssssssssssssssssssssssssassdasssssssssssssssssdasdasdasdasdASDasASASDASDASASsasdasdsasssasdsassssssssssssd
//instantfpc proyectointegrador.lprsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss